name: covid-19_detection

# Controls when the action will run. 
on: push


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  Testing-model-sanity:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        # Use bash as the shell
        shell: bash
        # Specify the working directory for the workflow
        working-directory: ./test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      - 
        name: Run Server
        working-directory: ./
        run: |
          export FLASK_APP=app.py
          python -m flask run
      -
        name: Test with pytest
        working-directory: ./test
        run: |
          pytest
